
create table if not exists nominations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  nominee_name text not null,
  nominee_org text,
  category_id text not null,
  reason text not null,
  nominator_name text not null,
  nominator_email text not null
);
